FORMAT: 1A
HOST: https://azarex.net/api/v1

# Azarex API
[Azarex API Documentation](https://docs.azarex.net) The official documentation of **Azarex** API.

# Group Authentication
The Authentication methods related to register, login, logout and delete account methods.
<!-- include(modules/auth.apib) -->

