+ Response 400 (application/json)

    + Body

            {
                "meta": {
                        "code": 400,
                        "message":"BAD_REQUEST"
                },
                "data": null
            }
