+ Response 401 (application/json)

    + Body

            {
                "meta": {
                        "code": 401,
                        "message":"UNAURHORIZED"
                },
                "data": null
            }
