+ Response 500 (application/json)

    + Body

            {
                "meta": {
                        "code": 500,
                        "message":"INTERNAL_ERROR"
                },
                "data": null
            }
